# Generated by Django 5.0.2 on 2024-02-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guggu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Massage',
            new_name='massage',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='UserEmail',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='UserName',
            new_name='username',
        ),
    ]
