# Generated by Django 5.0.2 on 2024-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guggu', '0002_rename_massage_contactus_massage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='myimages',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
