# Generated by Django 5.0.2 on 2024-03-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guggu', '0003_contactus_myimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='myimages',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
